### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rvetere** [tweedegolf/parsed_model_examples#1]
Hi there, i've did the following steps what i found out so far as there is no readme:

```
cd into react-three
npm install
npm run build
```

and BOOM:

```
sh: build/app.js: No such file or directory
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:794:14)
error Command failed with exit code 1.
```

**Comment by RichardLindhout** [comment]
I have the same problem.

**Comment by RichardLindhout** [comment]
```
rror: parsed-model-react-three@ build: `browserify js/app.js -t [ babelify --presets [es2015 react] --plugins [transform-class-properties] ] --debug | exorcist build/app.js.map | uglifyjs -c > build/app.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:897:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npm verb pkgid parsed-model-react-three
```
